### ISSUE TITLE
add support for parcel

### ISSUE THREAD

**Issue by riedel** [edge-ml/javascript#4]
import seems to fail when using parcel

**Comment by riedel** [comment]
Could that be the problem:
https://github.com/edge-ml/javascript/blob/f95bdccce5f7dd21d93fb7e0c08b77ecf5dc06be/index.js#L196 
?

**Comment by tk-king** [comment]
> Could that be the problem:
> 
> https://github.com/edge-ml/javascript/blob/f95bdccce5f7dd21d93fb7e0c08b77ecf5dc06be/index.js#L196
> 
> 
> ?

This is the issue.

**Comment by tk-king** [comment]
Rewrote the library to fix the issue.
