### ISSUE TITLE
add support for variable sampling rates 

### ISSUE THREAD

**Issue by riedel** [edge-ml/javascript#8]
would simply put window.length to a negative millisecond value

use _update_story to scan linear through the store to remove old sample (until time difference to now is reached).

**Comment by omeryagmurlu** [comment]
negative values in the `windowLength` parameter should now be considered as windows in milliseconds

**Comment by TobiasRoeddiger** [comment]
that sounds like an odd and unexpectable design choice? let's discuss it later

**Comment by riedel** [comment]
See https://github.com/edge-ml/ml/issues/11 .

IMHO using negative values is a bit strange, however, it makes the interface quite straight forwardly typed. A good alternative would be to use strings and use momentJS but this is overkill. 

Another alternative would be defaulting to 0 and using another named parameter. However, I think this is not much better.

**Comment by TobiasRoeddiger** [comment]
we decided to do the following:
- window size is an integer
- per default, it describes the window size in samples, we will overload the constructor and you can then change the window size type between as samples or as time based window through a seperate variable, not perfect but works

**Comment by riedel** [comment]
Sounds good, should probably use a string to define different window types and be extensible

**Comment by omeryagmurlu** [comment]
this should be fixed with https://github.com/edge-ml/javascript/commit/89c0a55b8e049724d3fb219f7c66b7004f7b4371 now. I've added windowingMode option with
